# general information
model_name: "Gazebo Standard Plane"
model_type: "Standard Plane Longitudinal Model"
model_class: "SimpleFixedWingModel"

  # all vectors in FRD body frame if not specified otherwise
model_config:
  mass: 20.0
  moment_of_inertia:
    Ixx: 25.0
    Iyy: 20.0
    Izz: 20.0
  power: 0.0015
  actuators:
    rotors:
      # All rotors in the same group will share the coefficients
      puller_:
        - rotor_4:
          description: "puller rotor"
          rotor_type: "RotorModel"
          dataframe_name: "u4"
          rotor_axis:
            - 1
            - 0
            - 0
          turning_direction: -1
          position:
            - 0.22
            - 0
            - 0

    control_surfaces:
      wing_:
        - control_surface_0:
          description: "aileron_right"
          dataframe_name: "u6"

        - control_surface_1:
          description: "aileron_left"
          dataframe_name: "u5"

        - control_surface_2:
          description: "elevator"
          dataframe_name: "u7"

        - control_surface_3:
          description: "rudder"
          dataframe_name: "u2"

        # - control_surface_4:
        #   description: "flaps"
        #   dataframe_name: "u3"

  aerodynamics:
    area: 2.0
    chord: 0.5
    stall_angle_deg: 20
    sig_scale_factor: 30

dynamics_model_config:
  optimizer_config:
    optimizer_class: "LinearRegressor"
  estimate_forces: True
  estimate_moments: False
  resample_freq: 50.0
  estimate_angular_acceleration: False
  data:
    required_ulog_topics:
      actuator_outputs:
        ulog_name:
          - "timestamp"
          - "output[2]" # Rudder
          # - "output[3]" # Flaps
          - "output[4]" # motor
          - "output[5]" # left aileron
          - "output[6]" # right aileron
          - "output[7]" # elevator
        dataframe_name:
          - "timestamp"
          - "u2"
          # - "u3"
          - "u4"
          - "u5"
          - "u6"
          - "u7"
        actuator_type:
          - "timestamp"
          - "control_surface"
          # - "control_surface"
          - "motor"
          - "control_surface"
          - "control_surface"
          - "control_surface"
      vehicle_local_position:
        ulog_name:
          - "timestamp"
          - "vx"
          - "vy"
          - "vz"
      vehicle_attitude:
        ulog_name:
          - "timestamp"
          - "q[0]"
          - "q[1]"
          - "q[2]"
          - "q[3]"
        dataframe_name:
          - "timestamp"
          - "q0"
          - "q1"
          - "q2"
          - "q3"
      vehicle_angular_velocity:
        ulog_name:
          - "timestamp"
          - "xyz[0]"
          - "xyz[1]"
          - "xyz[2]"
        dataframe_name:
          - "timestamp"
          - "ang_vel_x"
          - "ang_vel_y"
          - "ang_vel_z"
      sensor_combined:
        ulog_name:
          - "timestamp"
          - "accelerometer_m_s2[0]"
          - "accelerometer_m_s2[1]"
          - "accelerometer_m_s2[2]"
          - "gyro_rad[0]"
          - "gyro_rad[1]"
          - "gyro_rad[2]"
        dataframe_name:
          - "timestamp"
          - "acc_b_x"
          - "acc_b_y"
          - "acc_b_z"
          - "ang_acc_b_x"
          - "ang_acc_b_y"
          - "ang_acc_b_z"
